#!/usr/bin/env python3
"""Generate the reference from the same base descriptors and existing typed control registries."""
import argparse
import json
import pathlib
import re
from inventory import metadata, uncomment, ROOT

def string_expression(expression):
 return ''.join(json.loads(v) for v in re.findall(r'"(?:\\.|[^"\\])*"', expression))

def runtime_controls():
 text=uncomment((ROOT/'common/src/main/java/dev/vox/lss/common/config/RuntimeSettings.java').read_text())
 controls={}
 for match in re.finditer(r'new SettingKey\("(\w+)"(.*?)(?=new SettingKey|\n    private static String parseFarPlayersMode)',text,re.S):
  key,body=match.groups()
  note=re.search(r'},\s*((?:"(?:\\.|[^"\\])*"\s*\+?\s*)+)\)',body)
  if not note: raise ValueError('unrecognized runtime apply note: '+key)
  controls[key]=string_expression(note.group(1))
 return controls

def client_controls():
 text=uncomment((ROOT/'xplat/src/main/java/dev/vox/lss/config/menu/ClientOptionCatalog.java').read_text())
 controls={}
 for block in re.findall(r'(?:BoolSpec|IntSpec)\.builder\(.*?\.build\(\)',text,re.S):
  field=re.search(r'\.bind\(c\s*->\s*c\.(\w+)',block)
  if not field:
   # Rate slider getter intentionally transforms the stored CPS into an index.
   field=re.search(r'c\.(lodColumnsPerSecondLimit)',block)
  if not field: raise ValueError('unrecognized UI field binding')
  hook=re.search(r'\.saveHook\(SaveHook\.(\w+)\)',block)
  visibility=re.search(r'\.visibility\(Visibility\.(\w+)\)',block)
  name=re.search(r'\.name\("([^"]+)"\)',block)
  controls[field.group(1)]=(hook.group(1) if hook else 'SAVE',visibility.group(1) if visibility else 'ALWAYS',name.group(1))
 return controls

def rows():
 runtime=runtime_controls();client=client_controls()
 for side in ['Server','Client','Paper']:
  for d in metadata(side):
   if side=='Server' and d['key'] in runtime:
    d.update(exposure='RUNTIME',applyTiming=runtime[d['key']],restartRequired=False,
             validationBinding='RuntimeSettings.byName('+d['key']+').apply; ServerConfigBase.validate',
             controlAction='applyWithPersistenceOutcome + platform reconcile')
    if d['key']=='lodDistanceChunks' and any(m['key']=='lodDistanceChunksByWorld' for m in metadata('Server')):
     d.update(scopes=['SERVER','WORLD_DISTANCE'],inheritance='Paper: world name, dimension, global; Fabric/Neo: dimension, global')
   if side=='Client' and d['key'] in client:
    hook,visibility,name=client[d['key']]
    d.update(exposure='UI',documentationKey=name,applyTiming='client owner apply; '+hook,restartRequired=False,controlAction=hook,availability=visibility)
   yield side,d

def render():
 out=['# Configuration reference','','<!-- Generated by tools/settings/reference.py; do not edit. -->','',
 'Descriptors preserve the existing validators and typed runtime/UI controls. Values below are',
 'configured defaults and accepted domains; AUTO and inherited values resolve in their runtime',
 'context. LSS/VSS filename adoption remains unchanged. Serialized bindings report configured',
 'values, including generation staged for restart; server diagnostics separately report running',
 'generation and the configured restart value. A failed save means configured does not yet mean persisted.','',
 'Only distance supports explicitly selected world overrides where present. Presets select',
 'client-global or server-global scope; global batches reject world syntax. Advanced file-only',
 'settings are loaded on restart; metadata does not make them live controls.','',
 '| Scope | Key | Type / units | Default policy | Accepted domain / sentinels | Exposure |',
 '| --- | --- | --- | --- | --- | --- |']
 def cell(value):return str(value).replace('|','\\|').replace('\n',' ')
 data=list(rows())
 for side,d in data:
  out.append('| '+' | '.join(map(cell,[side,d['key'],d['type']+' / '+d['units'],d['defaultPolicy'],d['domain'],d['exposure']]))+' |')
 out+=['','| Key | Scope / inheritance | Availability | Apply timing / restart | Binding / action | Documentation or translation key |',
       '| --- | --- | --- | --- | --- | --- |']
 for side,d in data:
  out.append('| '+' | '.join(map(cell,[side+'.'+d['key'],', '.join(d['scopes'])+'; '+d['inheritance'],d['availability'],d['applyTiming']+'; restart='+str(d['restartRequired']).lower(),d['validationBinding']+'; '+d['controlAction'],d['documentationKey']]))+' |')
 out+=['','Runtime commands reject malformed integers, nonfinite decimals and unknown boolean/mode',
       'tokens before mutation. File normalization retains the documented fallback behavior.',
       'Both Sodium generations use the same ClientOptionCatalog order, typed bindings and SaveHook.',
       'Curved rate-slider indices are UI values; the persisted rate is columns per second.','']
 return '\n'.join(out)
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 target=ROOT/'docs/reference/settings.md';result=render()
 if args.check:
  if not target.exists() or target.read_text()!=result:parser.exit(1,'Settings reference is stale: run tools/settings/reference.py\n')
 else:target.parent.mkdir(parents=True,exist_ok=True);target.write_text(result)
