package dev.vox.lss.common.config;

/** Generated by tools/settings/inventory.py; existing typed controls override exposure. */
public final class PaperSerializedSettings {
    public static java.util.List<SettingDescriptor> descriptors() {
        return java.util.List.of(
            new SettingDescriptor("updateEvents", SettingDescriptor.Type.LIST, "identifiers", "paper.updateEvents", "List.of( \"org.bukkit.event.block.BlockPlaceEvent\", \"org.bukkit.event.block.BlockBreakEvent\", \"org.bukkit.event.block.BlockExplodeEvent\", \"org.bukkit.event.entity.EntityExplodeEvent\", \"org.bukkit.event.block.BlockBurnEvent\", \"org.bukkit.event.block.BlockFadeEvent\", \"org.bukkit.event.block.BlockFormEvent\", \"org.bukkit.event.block.BlockGrowEvent\", \"org.bukkit.event.block.BlockSpreadEvent\", \"org.bukkit.event.block.LeavesDecayEvent\", \"org.bukkit.event.block.BlockPistonExtendEvent\", \"org.bukkit.event.block.BlockPistonRetractEvent\", \"org.bukkit.event.entity.EntityChangeBlockEvent\", \"org.bukkit.event.world.StructureGrowEvent\" )", "Bukkit event class names; null -> empty list; unavailable/unrecognized classes skipped", "PaperConfig.validate", java.util.Set.of(SettingDescriptor.Scope.SERVER), "paper-global", "Paper/Folia only", "config file load; restart required", true, "config file load", SettingDescriptor.Exposure.ADVANCED)
        );
    }
    private PaperSerializedSettings() {}
}
