package dev.vox.lss.common.diagnostics;

/** Immutable owner-captured legacy diagnostics. Display-only strings are explicitly
 * excluded from export; every numeric counter remains available structurally. */
public record ClientDiagnosticSnapshot(
        long getAuditHeals,
        int getConfirmedRing,
        int getDirtyColumnCount,
        int getEffectiveLodDistanceChunks,
        int getEmptyColumnCount,
        long getFastScans,
        String getGovernedRateLabel,
        long getIngestParkedCount,
        int getLastBudget,
        int getLastIngestBacklog,
        int getLastQueued,
        int getMissingVanillaChunks,
        int getNearRings,
        long getQuadRingSkips,
        long getRateGated,
        double getReceiveRate,
        int getReceivedColumnCount,
        long getRegionSkips,
        int getRegionSpan,
        int getReopenedRingCount,
        double getRequestRate,
        int getScanRing,
        long getSummaryColumnsValidated,
        long getSummaryStampsApplied,
        long getSummaryStampsIgnored,
        long getSummaryTilesClean,
        long getSummaryTilesNoRegion,
        long getSummaryTilesStale,
        long getSummaryTilesUnknown,
        long getTotalColumnsReceived,
        long getTotalIngestFailures,
        long getTotalNotGenerated,
        long getTotalPositionsRequested,
        long getTotalSendCycles,
        long getTotalUpToDate,
        long getValveTrips,
        int getServerLodDistance,
        long getColumnsReceived,
        long getBytesReceived,
        long getColumnsDropped,
        long getConnectionStartMs,
        int getQueuedColumnCount,
        int rateCap,
        String describeCacheKey,
        String farPlayersLine,
        String farRendererLine,
        String xaeroDiagLine) {}
